### ISSUE TITLE
Why are sass/scss/Less all included?

### ISSUE THREAD

**Issue by ghost** [cuong1014/hyakusenrenma_test#1]
https://github.com/cuong1014/hyakusenrenma_test/blob/1aa72b3420bb68e336437838ba7d946a144be157/step1/scss/style.scss#L1

Please choose one pre-processor language and remove the others. Also, a more common directory structure will look like this:

```
dist
 - css
 - img
src
  - sass
  - img

index.html
```

`src` contains your pre-processed sass and images. `dist` contains your compiled css and optimized images. The index.html file will link to the css in the dist folder.

**Comment by cuong1014** [comment]
Remove less and scss and update the folder structure.
