### ISSUE TITLE
Import order

### ISSUE THREAD

**Issue by ghost** [cuong1014/hyakusenrenma_test#11]
https://github.com/cuong1014/hyakusenrenma_test/blob/d4765ffbc033c9e7bafde4f2e6a1b6ebb7de099a/step1/src/sass/app.sass#L4

Wouldn't it be better to import files in the `utilities` folder before `components` and other files that may depend on declarations in the `utilities` folder?

**Comment by cuong1014** [comment]
Yes! That's better
