### ISSUE TITLE
use class name instead of html selector

### ISSUE THREAD

**Issue by ghost** [cuong1014/hyakusenrenma_test#2]
https://github.com/cuong1014/hyakusenrenma_test/blob/1aa72b3420bb68e336437838ba7d946a144be157/step1/sass/style.sass#L25

This style will now apply to every `h1` element that you use across the site.
Wouldn't it be better to create a class name such as `.section-header` or a wrapper and apply this style?

**Comment by cuong1014** [comment]
Because this element is only one so I did not set class name.

**Comment by ghost** [comment]
@cuong1014 Please assume this code is part of a larger project where code like this will conflict with other parts. 

Please update the code accordingly.

**Comment by ghost** [comment]
Thank you for your update.
https://github.com/cuong1014/hyakusenrenma_test/blob/d4765ffbc033c9e7bafde4f2e6a1b6ebb7de099a/step1/src/sass/base/_globals.sass#L22
