### ISSUE TITLE
Avoid use of html selectors in sass

### ISSUE THREAD

**Issue by ghost** [cuong1014/hyakusenrenma_test#5]
https://github.com/cuong1014/hyakusenrenma_test/blob/1aa72b3420bb68e336437838ba7d946a144be157/step1/sass/style.sass#L70

It is best practice to avoid the use of html selectors in sass because it increases specificity and makes the sass dependent on the structure of the html.

please change use of `img`, `h2`, `h4` and `p` in the `.item` object to use class names.

`span` is a special case. You can ignore that for now.

**Comment by cuong1014** [comment]
Done
